export { default as About } from "./about/About";
export { default as AuthModal } from "./authModal/AuthModal";
export { default as Barbers } from "./barbers/Barbers";
export { default as Header } from "./header/Header";
export { default as OurServices } from "./ourServices/OurServices";
export { default as Navbar } from "./navbar/Navbar";
export { default as AppointmentCard } from "./appointmentCard/AppointmentCard";
export { default as MyCalendar } from "./myCalendar/MyCalendar";
export { default as Calendar } from "./myCalendar/Calendar";
